// <auto-generated />
using System;
using Bookstore.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bookstore.Infra.Data.Migrations
{
    [DbContext(typeof(BookstoreDbContext))]
    [Migration("20230925142337_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bookstore.Domain.Entities.Book", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Name");

                    b.Property<decimal>("Price")
                        .HasMaxLength(80)
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL")
                        .HasColumnName("Price");

                    b.HasKey("Id");

                    b.ToTable("Book", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "O maior romance da Literatura Espanhola é um clássico satírico de alta qualidade crítica.",
                            Name = "Dom Quixote",
                            Price = 29.90m
                        },
                        new
                        {
                            Id = 2,
                            Description = " Um dos principais clássicos de fantasia do mundo.",
                            Name = "O Senhor dos Anéis",
                            Price = 49.90m
                        },
                        new
                        {
                            Id = 3,
                            Description = " Um dos maiores clássicos infantis foi escrito e ilustrado pelo autor Antoine de Saint-Exupéry quando se encontrava exilado na América do Norte durante a II Guerra Mundial.",
                            Name = "O Pequeno Príncipe",
                            Price = 19.90m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Em Harry Potter e a Pedra Filosofal é apresentado Harry e todo o mundo fantástico a que ele pertence, assim como os perigos pelos quais o garoto está sujeito.",
                            Name = "Harry Potter e a Pedra Filosofal",
                            Price = 39.90m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
